version: "3.8"

services:
  mariadb:
    image: mariadb:10.11
    container_name: painel_forca_de_vendas_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: painel_forca_de_vendas_dev
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypass
    ports:
      - "3307:3306"
    volumes:
      - ./dump.sql:/docker-entrypoint-initdb.d/dump.sql
